---
title: "Assignment_1"
author: "brandon rumbarger"
date: "2026-01-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}

url <- "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"

adult <- read.csv(
  url,
  header = FALSE,
  stringsAsFactors = TRUE,
  strip.white = TRUE
)


colnames(adult) <- c(
  "age", "workclass", "fnlwgt", "education",
  "education_num", "marital_status", "occupation",
  "relationship", "race", "sex",
  "capital_gain", "capital_loss",
  "hours_per_week", "native_country", "income"
)
# Quantitative
summary(adult$age)
summary(adult$hours_per_week)

# Categorical 
table(adult$sex)
table(adult$income)
adult$log_hours <- log(adult$hours_per_week)
summary(adult$log_hours)

hist(
  adult$age,
  main = "Histogram of Age",
  xlab = "Age",
  col = "lightblue"
)

plot(
  adult$age,
  adult$hours_per_week,
  main = "Age vs Hours Worked per Week",
  xlab = "Age",
  ylab = "Hours per Week",
  pch = 19,
  col = "darkgreen"
)

```

